name: Engine - Test
on:
    push:
        paths:
            - '.github/workflows/engine-test.yml'
            - 'engine/**'
    pull_request:
        paths:
            - '.github/workflows/engine-test.yml'
            - 'engine/**'

defaults:
    run:
        working-directory: engine

jobs:
    lint_and_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '24'
            - uses: pnpm/action-setup@v4
              with:
                  version: 11
            - run: pnpm install
            - run: pnpm build
            - run: pnpm lint
            - run: pnpm test
